# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_macchiato"

# Inserts a blank line between shell prompts
add_newline = true

# Starship modules
[character]
success_symbol = "[[󱓞](green) ❯](peach)"
error_symbol = "[[󱓞](red) ❯](peach)"
vimcmd_symbol = "[󱓞 ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"
symbol = " "

[directory]
truncation_length = 4
truncate_to_repo = false
style = "bold teal"

[ruby]
symbol = "[](red) "

[golang]
symbol = "[](sky) "

[lua]
symbol = " "

[python]


[os]
disabled = true

[os.symbols]
Macos = "[](teal) "
Linux = "[](teal) "
Ubuntu = "[](teal) "

[gcloud]
disabled = true

[custom.gcloud]
command = "gcloud auth list --filter=status:ACTIVE --format='value(account)'"
when = "gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q ."
symbol = "[](blue) "
style = "blue"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
