# Minimal Starship config for inside tmux
# Since tmux provides path, git, and context info in status bars

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
palette = "catppuccin_macchiato"

# Inserts a blank line between shell prompts
add_newline = false

# Minimal format - just powerline rocket with status colors
format = """$character"""

# Simplified character - rocket + chevron with status colors (like full starship)
[character]
success_symbol = "[[󱓞](green) ❯](peach)"
error_symbol = "[[󱓞](red) ❯](peach)"
vimcmd_symbol = "[󱓞 ❮](subtext1)"

# Disable ALL modules except character - tmux handles everything else
[directory]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[hg_branch]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[buf]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true

[meson]
disabled = true

[spack]
disabled = true

[memory_usage]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[azure]
disabled = true

[crystal]
disabled = true

[sudo]
disabled = true

[cmd_duration]
disabled = true

[line_break]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[status]
disabled = true

[container]
disabled = true

[shell]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[localip]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[kubernetes]
disabled = true

[vcsh]
disabled = true

[fossil_branch]
disabled = true

[pijul_channel]
disabled = true

[os]
disabled = true

# Keep the color palette
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
