# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_macchiato"

# Make prompt commands bail out quickly if slow (milliseconds)
command_timeout = 600

# Inserts a blank line between shell prompts
add_newline = true

# Format the prompt to include custom modules in the desired order
format = """$all"""

# Starship modules
[character]
error_symbol = "[[󱓞](red) ❯](peach)"
success_symbol = "[[󱓞](green) ❯](peach)"
vimcmd_symbol = "[󱓞 ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"
symbol = " "

[directory]
style = "bold teal"
truncate_to_repo = false
truncation_length = 4

[nodejs]
disabled = true

[docker_context]
disabled = true

[git_status]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_commit]
disabled = true

[ruby]
disabled = true
symbol = "[](red) "

[golang]
disabled = true
symbol = "[](sky) "

[lua]
disabled = true
symbol = " "

[python]
disabled = true

[os]
disabled = true

[os.symbols]
Linux = "[](teal) "
Macos = "[](teal) "
Ubuntu = "[](teal) "

[gcloud]
disabled = true

[palettes.catppuccin_macchiato]
base = "#24273a"
blue = "#8aadf4"
crust = "#181926"
flamingo = "#f0c6c6"
green = "#a6da95"
lavender = "#b7bdf8"
mantle = "#1e2030"
maroon = "#ee99a0"
mauve = "#c6a0f6"
overlay0 = "#6e738d"
overlay1 = "#8087a2"
overlay2 = "#939ab7"
peach = "#f5a97f"
pink = "#f5bde6"
red = "#ed8796"
rosewater = "#f4dbd6"
sapphire = "#7dc4e4"
sky = "#91d7e3"
subtext0 = "#a5adcb"
subtext1 = "#b8c0e0"
surface0 = "#363a4f"
surface1 = "#494d64"
surface2 = "#5b6078"
teal = "#8bd5ca"
text = "#cad3f5"
yellow = "#eed49f"
