# AeroSpace Configuration
# Reference: https://nikitabobko.github.io/AeroSpace/guide

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Callbacks to update sketchybar immediately on workspace changes
after-login-command = []
after-startup-command = [
    'exec-and-forget sketchybar --trigger aerospace_workspace_change'
]

# Trigger sketchybar update on workspace changes
exec-on-workspace-change = [
    '/usr/bin/env', 'bash', '-c',
    'sketchybar --trigger aerospace_workspace_change'
]

# Gaps between windows
[gaps]
inner.horizontal = 6
inner.vertical =   6
outer.left =       6
outer.bottom =     6
outer.top =        6  # Small gap - sketchybar height handled by macOS
outer.right =      6

# Main modifier key: alt (option key)
# Using alt to avoid conflicts with cmd shortcuts in apps
[mode.main.binding]

# Focus windows (alt + vim keys)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows (alt + shift + vim keys)
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Window operations
alt-f = 'fullscreen'           # Fullscreen current window
alt-r = 'mode resize'          # Enter resize mode

# Layout modes (alt + shift + letter)
alt-shift-s = 'layout v_accordion'               # Stack vertically
alt-shift-a = 'layout h_accordion'               # Stack horizontally (accordion)
alt-shift-t = 'layout tiling'                    # Return to tiling
alt-shift-f = 'layout tiles horizontal vertical' # Flexible tiles

# Container operations (alt + shift + letter)
alt-shift-v = 'join-with down'   # Join with window below (vertical)
alt-shift-b = 'join-with right'  # Join with window to right (horizontal)

# Workspace switching (alt + number)
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace S'  # Slack workspace

# Move window to workspace (alt + shift + number)
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace S'

# Resize mode bindings
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
